language: rust
sudo: false

cache: cargo

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      env: DO_BENCHMARKS=1 ALLOW_WARNINGS=1
    # ensure wasm always builds
    - rust: stable
      env: TARGET=wasm32-unknown-unknown SKIP_TESTS=1
    # minimum rustc version
    - rust: 1.20.0
      env: SKIP_TESTS=1

script: bash -x ci/script.sh

notifications:
  email:
    on_success: never
